---
title: Jekyll-materialize
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'I''m a computer science student'

'
url: https://yahyatahix.github.io
baseurl: ''
logo: Yahya-<b>ETTAHI</b>
paginate: 5
paginate_path: "/blog/page:num/"
owner:
  email: yahyaettahi@student.emi.ac.ma
  facebook:
    show: false
    name: Yahya ETTAHI
    url: https://www.facebook.com/yahya.ettahi
  github:
    show: true
    username: yahyatahix
  twitter:
    show: true
    username: EttahiY
  disqus:
    show: false
    username: 
sass:
  sass_dir: _sass
  style: compressed
permalink: "/article/:title"
markdown: kramdown
highlighter: rouge
gems:
- jekyll-feed
- jemoji
theme: jekyll-theme-cayman
