---
title: Jekyll-materialize
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'I''m a computer science associate professor. I teach and do research
  in Distributed Systems, Autonomic Computing and Networking Protocols.

'
url: http://www.remisharrock.fr
baseurl: ''
logo: Rémi-<b>SHARROCK</b>
paginate: 5
paginate_path: "/blog/page:num/"
owner:
  email: remi.sharrock@telecom-paristech.fr
  facebook:
    show: false
    name: Rémi SHARROCK
    url: https://fb.me/remi.sharrock
  github:
    show: true
    username: remisharrock
  twitter:
    show: true
    username: remisharrock
  disqus:
    show: false
    username: remisharrock
sass:
  sass_dir: _sass
  style: compressed
permalink: "/article/:title"
markdown: kramdown
highlighter: rouge
gems:
- jekyll-feed
- jemoji
theme: jekyll-theme-cayman
